### ISSUE TITLE
Persist New data for frontend from csv file to db

### ISSUE THREAD

**Issue by jovialcore** [jovialcore/whatcompstack-BE#35]
We have a new data for frontend stacks that include :
- Company name, logo, about, and frontend stacks. We want to be able to upload this as csv file via a form input and data should be persisted folowing the database design/structure.
If you are interested, send me your  [email me.](chidideveloper@gmail.com)

**Comment by devMuhammad05** [comment]
Do you mean that this should be possible from the admin side of the project?

**Comment by jovialcore** [comment]
> Do you mean that this should be possible from the admin side of the project?

Yes. that is what I mean.
